spring:
  datasource:
    url: "${DB_URL}"
    username: "${USERNAME}"
    password: "${PASSWORD}"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    
server:
  servlet:
    contextPath: /
  error:
    whitelabel: 
      enabled: false







